POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcm1hYW5tYWxpazFAZ21haWwuY29tIiwiZXhwIjoxNzQ1ODY2MTM2LCJ1c2VySWQiOjF9.6Ou3Gih9XkDecZCXYtvcG5M1sQ10as0PDjbBnGyEoW8

{
    "Name":"Test Meetup 2",
    "Description":"Go meetup again",
    "location":"Srinagar"
}