PUT  http://localhost:8080/events/5
Content-Type: application/json

{
    "Name":"Updated Test Meetup 5 three times",
    "Description":"updated Location three times",
    "location":"updated this three times"
}